# Generated by Django 2.2.19 on 2021-03-11 08:44

import collections
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_program_restrictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data',
            field=jsonfield.fields.JSONField(default={}, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
    ]
