# Generated by Django 2.2 on 2020-04-21 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_therapist_20200311_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_therapist',
            field=models.BooleanField(default=False, verbose_name='is therapist'),
        ),
        migrations.AlterField(
            model_name='user',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL, verbose_name='therapist'),
        ),
    ]
