# Generated by Django 2.2.17 on 2021-08-10 13:09

import collections
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_secondary_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data',
            field=jsonfield.fields.JSONField(default={}, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
    ]
