# Generated by Django 2.2.17 on 2021-08-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20150218_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='post_value',
            field=models.CharField(blank=True, max_length=16384, verbose_name='post value'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pre_value',
            field=models.CharField(blank=True, max_length=16384, verbose_name='pre value'),
        ),
    ]
