# Generated by Django 2.2.19 on 2021-03-09 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('system', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='programuseraccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='program',
            name='cover_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_cover_images', to=settings.FILER_IMAGE_MODEL, verbose_name='cover image'),
        ),
        migrations.AddField(
            model_name='program',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site', verbose_name='site'),
        ),
        migrations.AddField(
            model_name='program',
            name='users',
            field=models.ManyToManyField(through='system.ProgramUserAccess', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
        migrations.AddField(
            model_name='content',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Can optionally be bound to a specific program', null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Program', verbose_name='program'),
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
            ],
            options={
                'verbose_name': 'code',
                'verbose_name_plural': 'codes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('system.content',),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
            ],
            options={
                'verbose_name': 'e-mail',
                'verbose_name_plural': 'e-mails',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('system.content',),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('system.content',),
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
            ],
            options={
                'verbose_name': 'SMS',
                'verbose_name_plural': 'SMSs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('system.content',),
        ),
    ]
