# Generated by Django 2.0.13 on 2020-01-16 22:11

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_program_from_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='title')),
                ('display_title', models.CharField(max_length=64, verbose_name='display title')),
                ('chapter_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'chapter',
                'verbose_name_plural': 'chapters',
                'ordering': ['chapter_order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='title')),
                ('display_title', models.CharField(max_length=64, verbose_name='display title')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
            },
        ),
        migrations.AlterField(
            model_name='program',
            name='style',
            field=models.CharField(blank=True, choices=[('css/style.css', 'Default stylesheet'), ('css/style-nalokson.css', 'Nalokson'), ('css/style-miksmaster.css', 'Miksmaster'), ('css/style-miksmaster-alt.css', 'Miksmaster alternate')], max_length=128, null=True, verbose_name='stylesheet'),
        ),
        migrations.AddField(
            model_name='module',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Program', verbose_name='program'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='module',
            field=adminsortable.fields.SortableForeignKey(blank=True, help_text='Can optionally be bound to a specific module', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Module', verbose_name='module'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Can optionally be bound to a specific program', null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Program', verbose_name='program'),
        ),
        migrations.AddField(
            model_name='content',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Chapter', verbose_name='chapter'),
        ),
    ]
