# Generated by Django 2.2.19 on 2021-03-11 08:44

import collections
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('system', '0016_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='about'),
        ),
        migrations.AddField(
            model_name='program',
            name='cover_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_cover_images', to=settings.FILER_IMAGE_MODEL, verbose_name='cover image'),
        ),
        migrations.AddField(
            model_name='program',
            name='is_lock',
            field=models.BooleanField(default=False, verbose_name='is program lock'),
        ),
        migrations.AddField(
            model_name='session',
            name='interval',
            field=models.IntegerField(default=0, verbose_name='interval delta'),
        ),
        migrations.AddField(
            model_name='variable',
            name='is_array',
            field=models.BooleanField(default=False, verbose_name='is array'),
        ),
        migrations.AddField(
            model_name='variable',
            name='optional_values',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='optional values'),
        ),
        migrations.AlterField(
            model_name='content',
            name='data',
            field=jsonfield.fields.JSONField(default=[], load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
        migrations.AlterField(
            model_name='program',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site', verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='program',
            name='style',
            field=models.CharField(blank=True, choices=[('css/style.css', 'Default stylesheet'), ('css/style-nalokson.css', 'Nalokson'), ('css/style-miksmaster.css', 'Miksmaster'), ('css/style-miksmaster-alt.css', 'Miksmaster alternate')], max_length=128, null=True, verbose_name='stylesheet'),
        ),
        migrations.AlterField(
            model_name='session',
            name='data',
            field=jsonfield.fields.JSONField(default='{"nodes": [], "edges": []}', load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[^ ]+$', 'No spaces allowed')], verbose_name='name'),
        ),
    ]
