# Generated by Django 2.0.13 on 2020-02-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_auto_20200117_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='is_array',
            field=models.BooleanField(default=False, verbose_name='is array'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_order',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='style',
            field=models.CharField(blank=True, choices=[('css/style.css', 'Default stylesheet'), ('css/style-nalokson-ltr.css', 'New-Nalokson'), ('css/style-nalokson-rtl.css', 'RTL-Nalokson'), ('css/style-nalokson.css', 'Nalokson'), ('css/style-miksmaster.css', 'Miksmaster'), ('css/style-miksmaster-alt.css', 'Miksmaster alternate')], max_length=128, null=True, verbose_name='stylesheet'),
        ),
    ]
