# Generated by Django 2.2 on 2020-04-21 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_auto_20200223_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramGoldVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golden_type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], max_length=10, verbose_name='Golden type')),
                ('therapist_can_edit', models.BooleanField(default=False, verbose_name='Therapist can edit')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Program', verbose_name='program')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Variable', verbose_name='variable')),
            ],
            options={
                'verbose_name': 'gold variable',
                'verbose_name_plural': 'gold variables',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='gold_variables',
            field=models.ManyToManyField(related_name='program_golds', through='system.ProgramGoldVariable', to='system.Variable', verbose_name='gold variables'),
        ),
    ]
