# Generated by Django 2.2 on 2020-06-16 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_program_is_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site', verbose_name='site'),
        ),
    ]
