# Generated by Django 2.2 on 2020-06-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_auto_20200616_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='optional_values',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='optional values'),
        ),
    ]
