# Generated by Django 2.2 on 2020-06-16 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0021_variable_optional_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('message', models.CharField(max_length=512, verbose_name='message')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_notifications', to=settings.AUTH_USER_MODEL, verbose_name='patient')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Program', verbose_name='program')),
                ('therapist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapist_notifications', to=settings.AUTH_USER_MODEL, verbose_name='therapist')),
            ],
            options={
                'verbose_name': 'therapist notification',
                'verbose_name_plural': 'therapist notifications',
            },
        ),
    ]
