# Generated by Django 2.2 on 2020-07-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_auto_20200624_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file_data',
            field=models.BinaryField(default=None, null=True, verbose_name='file data'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_name',
            field=models.TextField(default=None, null=True, verbose_name='file name'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_type',
            field=models.TextField(default=None, null=True, verbose_name='file type'),
        ),
    ]
