# Generated by Django 2.2 on 2020-08-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_auto_20200730_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_recurrent',
            field=models.BooleanField(default=False, verbose_name='is recurrent task'),
        ),
    ]
