# Generated by Django 2.2.17 on 2021-08-10 14:15

import collections
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0028_auto_20200824_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='max_entries',
            field=models.IntegerField(blank=True, null=True, verbose_name='array max entries'),
        ),
        migrations.AlterField(
            model_name='content',
            name='data',
            field=jsonfield.fields.JSONField(default=[], load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
        migrations.AlterField(
            model_name='session',
            name='data',
            field=jsonfield.fields.JSONField(default={'edges': [], 'nodes': []}, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
    ]
