# Generated by Django 2.2.19 on 2021-03-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('time', models.DateTimeField(verbose_name='time')),
                ('log', models.TextField(blank=True, null=True, verbose_name='log')),
            ],
            options={
                'verbose_name': 'codelog',
                'verbose_name_plural': 'codelogs',
            },
        ),
    ]
