# Generated by Django 2.2.19 on 2021-03-09 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0002_auto_20210309_1429'),
        ('codelogs', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='codelog',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Code', verbose_name='code'),
        ),
        migrations.AddField(
            model_name='codelog',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='sender'),
        ),
        migrations.AddField(
            model_name='codelog',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='subject'),
        ),
    ]
